import { realtimeMiddleware } from "@inngest/realtime/middleware";
import { EventSchemas, Inngest } from "inngest";
import {
  analyzeFreelanceResponseDataSchema,
  bufferFlushDataSchema,
  candidateOfferSendDataSchema,
  candidateWelcomeBatchDataSchema,
  candidateWelcomeDataSchema,
  collectChatIdsDataSchema,
  conversationMessageReceivedDataSchema,
  conversationMessageSendDataSchema,
  generateInvitationDataSchema,
  interviewAnalysisDataSchema,
  interviewCompleteDataSchema,
  interviewSendQuestionDataSchema,
  messageBufferedDataSchema,
  parseMissingContactsDataSchema,
  parseNewResumesDataSchema,
  refreshSingleResumeDataSchema,
  responseScreenDataSchema,
  screenAllResponsesDataSchema,
  screenNewResponsesDataSchema,
  screenResponsesBatchDataSchema,
  sendFreelanceNotificationDataSchema,
  telegramAuthErrorDataSchema,
  telegramUnidentifiedMessageSendDataSchema,
  typingActivityDataSchema,
  vacancyRequirementsExtractDataSchema,
  vacancyResponsesRefreshDataSchema,
  vacancyUpdateActiveDataSchema,
  vacancyUpdateSingleDataSchema,
  verifyHHCredentialsDataSchema,
  voiceTranscriptionDataSchema,
} from "./types";

// Создание Inngest клиента с Zod схемами для типобезопасных событий
export const inngest = new Inngest({
  id: "qbs-autonaim",
  name: "QBS Автонайм Jobs",
  middleware: [realtimeMiddleware()],
  schemas: new EventSchemas().fromSchema({
    "vacancy/requirements.extract": vacancyRequirementsExtractDataSchema,
    "response/screen": responseScreenDataSchema,
    "response/screen.new": screenNewResponsesDataSchema,
    "response/screen.all": screenAllResponsesDataSchema,
    "response/screen.batch": screenResponsesBatchDataSchema,
    "response/resume.parse-new": parseNewResumesDataSchema,
    "response/resume.refresh": refreshSingleResumeDataSchema,
    "response/contacts.parse-missing": parseMissingContactsDataSchema,
    "vacancy/update.active": vacancyUpdateActiveDataSchema,
    "vacancy/update.single": vacancyUpdateSingleDataSchema,
    "vacancy/responses.refresh": vacancyResponsesRefreshDataSchema,
    "vacancy/chat-ids.collect": collectChatIdsDataSchema,
    "candidate/welcome": candidateWelcomeDataSchema,
    "candidate/welcome.batch": candidateWelcomeBatchDataSchema,
    "candidate/offer.send": candidateOfferSendDataSchema,
    "freelance/response.analyze": analyzeFreelanceResponseDataSchema,
    "freelance/invitation.generate": generateInvitationDataSchema,
    "freelance/notification.send": sendFreelanceNotificationDataSchema,
    "telegram/message.received": conversationMessageReceivedDataSchema,
    "telegram/message.send": conversationMessageSendDataSchema,
    "telegram/message.send.by-username":
      telegramUnidentifiedMessageSendDataSchema,
    "telegram/voice.transcribe": voiceTranscriptionDataSchema,
    "telegram/interview.analyze": interviewAnalysisDataSchema,
    "telegram/interview.send-question": interviewSendQuestionDataSchema,
    "telegram/interview.complete": interviewCompleteDataSchema,
    "telegram/auth.error": telegramAuthErrorDataSchema,
    "integration/verify-hh-credentials": verifyHHCredentialsDataSchema,
    "interview/message.buffered": messageBufferedDataSchema,
    "interview/typing.activity": typingActivityDataSchema,
    "interview/buffer.flush": bufferFlushDataSchema,
    "web/interview.send-question": interviewSendQuestionDataSchema,
    "web/interview.complete": interviewCompleteDataSchema,
  }),
});
