import { cx } from "class-variance-authority";
import { twMerge } from "tailwind-merge";

export const cn = (...inputs: Parameters<typeof cx>) => twMerge(cx(inputs));

// Export all components
export * from "./accordion";
export * from "./alert";
export * from "./alert-dialog";
export * from "./aspect-ratio";
export * from "./avatar";
export * from "./badge";
export * from "./breadcrumb";
export * from "./button";
export * from "./button-group";
export * from "./calendar";
export * from "./candidate-avatar";
export * from "./card";
export * from "./carousel";
export { useCarousel, type CarouselApi } from "./carousel";
export * from "./chart";
export * from "./checkbox";
export * from "./collapsible";
export * from "./command";
export * from "./context-menu";
export * from "./delete-vacancy-dialog";
export * from "./dialog";
export * from "./drawer";
export * from "./dropdown-menu";
export * from "./empty";
export * from "./field";
export * from "./form";
export * from "./hover-card";
export * from "./info-tooltip";
export * from "./input";
export * from "./input-group";
export * from "./input-otp";
export * from "./integration-icon";
export * from "./item";
export * from "./kbd";
export * from "./label";
export * from "./menubar";
export * from "./navigation-menu";
export * from "./pagination";
export * from "./password-input";
export * from "./popover";
export * from "./progress";
export * from "./radio-group";
export * from "./resizable";
export * from "./scroll-area";
export * from "./select";
export * from "./separator";
export * from "./sheet";
export * from "./sidebar";
export * from "./skeleton";
export * from "./slider";
export { SonnerToaster } from "./sonner";
export * from "./spinner";
export * from "./switch";
export * from "./table";
export * from "./tabs";
export * from "./textarea";
export * from "./theme";
export * from "./radix-toast";
export { Toaster } from "./toaster";
export * from "./toggle";
export * from "./toggle-group";
export * from "./tooltip";
export * from "./tooltip-markdown";
export { useIsMobile } from "./use-mobile";
export { useToast, toast } from "./use-toast";
